#!/usr/bin/env python3
"""Updates .vscode/launch.json configurations dynamically based on the compiled target."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LAUNCH_JSON_PATH = ROOT / ".vscode" / "launch.json"
GENERATED_NOTICE = (
    "// Generated by tools/update_launch.py for the last successfully built "
    "debug target. Do not edit manually.\n"
)


def launch_configurations(preset: str) -> list[dict[str, object]] | None:
    if preset == "ch32h417-riscv-gcc":
        return [
            {
                "name": "CH32H417 Hart 1 (V5F): OpenOCD load",
                "cwd": "${workspaceFolder}",
                "type": "cortex-debug",
                "request": "launch",
                "servertype": "openocd",
                "serverpath": "${workspaceFolder}/tools/openocd_wch/bin/openocd.exe",
                "gdbPath": "${workspaceFolder}/tools/riscv_gcc/bin/riscv-none-elf-gdb.exe",
                "executable": "${workspaceFolder}/build/ch32h417-riscv-gcc/src/port/ch32h417/ch32h417_bringup.elf",
                "configFiles": [
                    "${workspaceFolder}/src/port/ch32h417/debug/ch32h417_v5f_wch.cfg"
                ],
                "gdbTarget": "localhost:3333",
                "runToEntryPoint": "main",
                "overrideLaunchCommands": [
                    "monitor halt",
                    "monitor reg dcsr 0x400003",
                    "monitor reg pc 0x00010000",
                    "load",
                    "compare-sections",
                    "tbreak main",
                    "continue"
                ],
                "overrideResetCommands": [
                    "monitor halt",
                    "monitor reg dcsr 0x400003",
                    "monitor reg pc 0x00010000",
                    "load",
                    "tbreak main",
                    "continue"
                ]
            }
        ]
    if preset == "am243x-ticlang":
        return [
            {
                "name": "AM243x R5FSS0-0: OpenOCD load at reset",
                "cwd": "${workspaceFolder}",
                "type": "cortex-debug",
                "request": "launch",
                "servertype": "openocd",
                "serverpath": "${workspaceFolder}/tools/openocd/bin/openocd.exe",
                "gdbPath": "${workspaceFolder}/tools/arm_gcc/bin/arm-none-eabi-gdb.exe",
                "armToolchainPath": "${workspaceFolder}/tools/arm_gcc/bin",
                "executable": "${workspaceFolder}/build/am243x-ticlang/src/applications/am243x_bringup/am243x_bringup.out",
                "configFiles": [
                    "${workspaceFolder}/tools/gdb/xsdk_openocd_am243x.cfg"
                ],
                "searchDir": [
                    "${workspaceFolder}/tools/openocd/openocd/scripts"
                ],
                "preLaunchTask": "xSDK: build AM243x bringup (TI clang)",
                "overrideLaunchCommands": [
                    "monitor halt",
                    "load",
                    "set $cpsr = 0x1d3",
                    "set $pc = _vectors",
                    "break xRTOS_Port_AM243x_Reset_Handler"
                ],
                "serverStartupDelay": 6000,
                "showDevDebugOutput": "raw"
            },
            {
                "name": "AM243x R5FSS0-0: OpenOCD attach",
                "cwd": "${workspaceFolder}",
                "type": "cortex-debug",
                "request": "attach",
                "servertype": "openocd",
                "serverpath": "${workspaceFolder}/tools/openocd/bin/openocd.exe",
                "gdbPath": "${workspaceFolder}/tools/arm_gcc/bin/arm-none-eabi-gdb.exe",
                "armToolchainPath": "${workspaceFolder}/tools/arm_gcc/bin",
                "executable": "${workspaceFolder}/build/am243x-ticlang/src/applications/am243x_bringup/am243x_bringup.out",
                "configFiles": [
                    "${workspaceFolder}/tools/gdb/xsdk_openocd_am243x.cfg"
                ],
                "searchDir": [
                    "${workspaceFolder}/tools/openocd/openocd/scripts"
                ],
                "serverStartupDelay": 6000,
                "showDevDebugOutput": "raw"
            }
        ]
    return None


def update_launch(preset: str, launch_json_path: Path = LAUNCH_JSON_PATH) -> bool:
    """Replace launch configurations when preset has a debug configuration."""
    configurations = launch_configurations(preset)
    if configurations is None:
        return False

    data = {
        "version": "0.2.0",
        "configurations": configurations,
    }
    launch_json_path.parent.mkdir(parents=True, exist_ok=True)
    launch_json_path.write_text(
        f"{GENERATED_NOTICE}{json.dumps(data, indent=4)}\n",
        encoding="utf-8",
    )
    print(f"Updated VS Code launch.json for target preset: {preset}")
    return True


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: update_launch.py <preset>", file=sys.stderr)
        return 1

    try:
        update_launch(sys.argv[1])
    except Exception as error:
        print(f"Error updating launch.json: {error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
